"""Added status column to ConstructionDetails

Revision ID: ed43ab4bd738
Revises: 
Create Date: 2025-04-20 12:38:21.619006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed43ab4bd738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_details', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
